# Generated by cucumber-sinatra. (2015-01-07 11:51:26 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/battleships.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Battleships2

class Battleships2World
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Battleships2World.new
end
